# Generated by Django 4.2.7 on 2025-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified'], name='users_is_emai_476443_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active'], name='users_last_ac_323696_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_6541e9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_ratings_given'], name='users_total_r_7db483_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['average_rating'], name='users_average_ede59c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_of_birth'], name='users_date_of_e7181c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_profile_public'], name='user_profil_is_prof_3efebc_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email_notifications'], name='user_profil_email_n_fdf774_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['recommendation_emails'], name='user_profil_recomme_9e65bd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['exclude_adult_content'], name='user_profil_exclude_6f73d1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['min_rating_threshold'], name='user_profil_min_rat_d2d3bd_idx'),
        ),
    ]
