# Generated by Django 4.2.7 on 2025-08-31 19:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import images.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=images.models.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('downloads_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('link', 'Direct Link'), ('email', 'Email'), ('social', 'Social Media'), ('embed', 'Embed Code')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='images.imageupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.IntegerField(default=0, help_text='-100 to 100')),
                ('contrast', models.IntegerField(default=0, help_text='-100 to 100')),
                ('saturation', models.IntegerField(default=0, help_text='-100 to 100')),
                ('hue', models.IntegerField(default=0, help_text='-180 to 180')),
                ('sharpness', models.IntegerField(default=0, help_text='-100 to 100')),
                ('blur', models.IntegerField(default=0, help_text='0 to 100')),
                ('filter_applied', models.CharField(choices=[('none', 'None'), ('vintage', 'Vintage'), ('black_white', 'Black & White'), ('sepia', 'Sepia'), ('vibrant', 'Vibrant'), ('cool', 'Cool'), ('warm', 'Warm'), ('dramatic', 'Dramatic')], default='none', max_length=20)),
                ('crop_x', models.IntegerField(default=0)),
                ('crop_y', models.IntegerField(default=0)),
                ('crop_width', models.IntegerField(blank=True, null=True)),
                ('crop_height', models.IntegerField(blank=True, null=True)),
                ('rotation', models.IntegerField(default=0, help_text='Degrees: 0, 90, 180, 270')),
                ('flip_horizontal', models.BooleanField(default=False)),
                ('flip_vertical', models.BooleanField(default=False)),
                ('quality', models.IntegerField(default=85, help_text='1 to 100')),
                ('watermark_enabled', models.BooleanField(default=False)),
                ('watermark_text', models.CharField(blank=True, max_length=100)),
                ('watermark_opacity', models.IntegerField(default=50, help_text='0 to 100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='images.imageupload')),
            ],
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size', models.IntegerField(default=10485760)),
                ('allowed_formats', models.JSONField(default=images.models.get_default_allowed_formats)),
                ('auto_optimize', models.BooleanField(default=True)),
                ('default_privacy', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=20)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exif_data', models.JSONField(blank=True, default=dict)),
                ('color_palette', models.JSONField(blank=True, default=list)),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('focal_length', models.CharField(blank=True, max_length=50)),
                ('aperture', models.CharField(blank=True, max_length=50)),
                ('iso', models.CharField(blank=True, max_length=50)),
                ('shutter_speed', models.CharField(blank=True, max_length=50)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='images.imageupload')),
            ],
        ),
        migrations.CreateModel(
            name='ImageLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='images.imageupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='images.imageupload')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='images.imagecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageCollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagecollection')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imageupload')),
            ],
            options={
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.imageupload'),
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='images',
            field=models.ManyToManyField(related_name='collections', through='images.ImageCollectionItem', to='images.imageupload'),
        ),
        migrations.AddField(
            model_name='imagecollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['user', '-created_at'], name='images_imag_user_id_dc930a_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['privacy', '-created_at'], name='images_imag_privacy_a8fe6e_idx'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['status'], name='images_imag_status_9ffc58_idx'),
        ),
        migrations.AddIndex(
            model_name='imageshare',
            index=models.Index(fields=['share_token'], name='images_imag_share_t_1df2c9_idx'),
        ),
        migrations.AddIndex(
            model_name='imageshare',
            index=models.Index(fields=['image', '-created_at'], name='images_imag_image_i_8e57c3_idx'),
        ),
        migrations.AddIndex(
            model_name='imagelike',
            index=models.Index(fields=['image', '-created_at'], name='images_imag_image_i_9daae7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagelike',
            unique_together={('user', 'image')},
        ),
        migrations.AddIndex(
            model_name='imagecomment',
            index=models.Index(fields=['image', '-created_at'], name='images_imag_image_i_161028_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagecollectionitem',
            unique_together={('collection', 'image')},
        ),
        migrations.AddIndex(
            model_name='imagecollection',
            index=models.Index(fields=['user', '-updated_at'], name='images_imag_user_id_ac7541_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecollection',
            index=models.Index(fields=['privacy', '-updated_at'], name='images_imag_privacy_0ef59f_idx'),
        ),
    ]
