# Generated by Django 5.2.5 on 2025-08-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_title_179e04_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_release_e1d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='movies_year_1feb9b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['average_rating'], name='movies_average_99136b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='movies_tmdb_id_472987_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['imdb_id'], name='movies_imdb_id_7ab72f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='moviecast',
            unique_together={('movie', 'person', 'role')},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='ratings_rating_105b29_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_at'], name='ratings_created_7f1288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
