# Generated by Django 4.2.7 on 2025-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
