# Generated by Django 4.2.7 on 2025-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_runtime_movie_duration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='movies_popular_befb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date', 'average_rating'], name='movies_release_20dcae_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity', 'average_rating'], name='movies_popular_1f7570_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['duration'], name='movies_duratio_87dab3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['budget'], name='movies_budget_b66964_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['revenue'], name='movies_revenue_b4a706_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['status'], name='movies_status_da1881_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['adult'], name='movies_adult_f1cafb_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['movie', 'role'], name='movie_cast_movie_i_23d69e_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['person', 'role'], name='movie_cast_person__75b68b_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['role'], name='movie_cast_role_e93ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='moviecast',
            index=models.Index(fields=['order'], name='movie_cast_order_1ceedb_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'rating'], name='ratings_user_id_b7af4c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'rating'], name='ratings_movie_i_e0416e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', 'created_at'], name='ratings_user_id_7f9f81_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'created_at'], name='ratings_movie_i_0ad3a5_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'added_at'], name='watchlists_user_id_2cb387_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['movie'], name='watchlists_movie_i_4a371e_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['added_at'], name='watchlists_added_a_f85c60_idx'),
        ),
    ]
