# Generated by Django 4.2.7 on 2025-08-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movies_popular_befb0b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=50)),
                ('site', models.CharField(default='YouTube', max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('official', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Trailer',
                'verbose_name_plural': 'Trailers',
                'db_table': 'trailers',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['movie', 'type'], name='trailers_movie_i_043b0b_idx'), models.Index(fields=['published_at'], name='trailers_publish_b8e876_idx')],
                'unique_together': {('movie', 'key')},
            },
        ),
    ]
