# Generated by Django 4.2.7 on 2025-08-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_implicit',
            field=models.BooleanField(default=False, help_text='Rating derived from user feedback rather than explicit rating'),
        ),
    ]
