# Generated by Django 5.2.5 on 2025-08-27 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('irrelevant', 'Irrelevant'), ('already_seen', 'Already Seen'), ('not_interested', 'Not Interested')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recommendation Feedback',
                'verbose_name_plural': 'Recommendation Feedback',
                'db_table': 'recommendation_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('genre_similarity', models.FloatField(default=0.0)),
                ('cast_similarity', models.FloatField(default=0.0)),
                ('director_similarity', models.FloatField(default=0.0)),
                ('year_similarity', models.FloatField(default=0.0)),
                ('rating_similarity', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Similar Movie',
                'verbose_name_plural': 'Similar Movies',
                'db_table': 'similar_movies',
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='TrendingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('watchlist_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('trending_score', models.FloatField(default=0.0)),
                ('popularity_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trending Movie',
                'verbose_name_plural': 'Trending Movies',
                'db_table': 'trending_movies',
                'ordering': ['-trending_score', '-date'],
            },
        ),
        migrations.CreateModel(
            name='UserMovieInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed'), ('like', 'Liked'), ('dislike', 'Disliked'), ('watchlist_add', 'Added to Watchlist'), ('watchlist_remove', 'Removed from Watchlist'), ('rate', 'Rated'), ('share', 'Shared'), ('search', 'Searched'), ('click', 'Clicked')], max_length=20)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Movie Interaction',
                'verbose_name_plural': 'User Movie Interactions',
                'db_table': 'user_movie_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.JSONField(blank=True, default=dict)),
                ('preferred_languages', models.JSONField(blank=True, default=list)),
                ('min_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('max_runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('min_year', models.PositiveIntegerField(blank=True, null=True)),
                ('max_year', models.PositiveIntegerField(blank=True, null=True)),
                ('include_adult', models.BooleanField(default=False)),
                ('recommendation_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_used', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based Filtering'), ('hybrid', 'Hybrid Approach'), ('popularity', 'Popularity-Based'), ('trending', 'Trending Movies')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score of the recommendation (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True, help_text='Explanation for the recommendation')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
