# Generated by Django 5.2.5 on 2025-08-27 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationfeedback',
            name='recommendation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.recommendation'),
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='movie1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='similarmovie',
            name='movie2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='trendingmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_data', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='usermovieinteraction',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='usermovieinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_f904a9_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['algorithm_used'], name='recommendat_algorit_658b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['confidence_score'], name='recommendat_confide_ac1727_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['is_viewed'], name='recommendat_is_view_186dee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='similarmovie',
            index=models.Index(fields=['movie1', 'similarity_score'], name='similar_mov_movie1__3040a9_idx'),
        ),
        migrations.AddIndex(
            model_name='similarmovie',
            index=models.Index(fields=['similarity_score'], name='similar_mov_similar_86f7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarmovie',
            unique_together={('movie1', 'movie2')},
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['date', 'period_type'], name='trending_mo_date_9bd704_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['trending_score'], name='trending_mo_trendin_487245_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingmovie',
            index=models.Index(fields=['popularity_rank'], name='trending_mo_popular_204406_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trendingmovie',
            unique_together={('movie', 'date', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['user', 'interaction_type'], name='user_movie__user_id_5661a7_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['movie', 'interaction_type'], name='user_movie__movie_i_9b73a6_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['created_at'], name='user_movie__created_08f1e7_idx'),
        ),
    ]
