# Generated by Django 4.2.7 on 2025-08-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='max_runtime',
            new_name='max_duration',
        ),
    ]
