# Generated by Django 4.2.7 on 2025-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_rename_max_runtime_userpreference_max_duration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['recommendation'], name='recommendat_recomme_27dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['feedback_type'], name='recommendat_feedbac_19a855_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['created_at'], name='recommendat_created_a6c2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationfeedback',
            index=models.Index(fields=['feedback_type', 'created_at'], name='recommendat_feedbac_08b20f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['user', 'created_at'], name='user_movie__user_id_bcaf14_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['movie', 'created_at'], name='user_movie__movie_i_544df1_idx'),
        ),
        migrations.AddIndex(
            model_name='usermovieinteraction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='user_movie__interac_300f57_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user'], name='user_prefer_user_id_63441d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['recommendation_frequency'], name='user_prefer_recomme_aa1250_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['updated_at'], name='user_prefer_updated_ebdf5e_idx'),
        ),
    ]
